<a href="https://colab.research.google.com/github/tanvi3006/Development-of-AI-Based-Knowledge-Retrieval-Platform-with-Query-Resolution-System/blob/main/SQL_Task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Create two databases for sql queries to be performed on it in google colab

--- Database 1: company.db (employees table) ---

   id     name   department  salary
0   1    Alice  Engineering   90000
1   2      Bob        Sales   70000
2   3  Charlie  Engineering   95000
3   4    Diana    Marketing   65000

--- Database 2: inventory.db (products table) ---

   product_id product_name     category  stock   price
0         101       Laptop  Electronics     15  1200.0
1         102   Desk Chair    Furniture     30   150.0
2         103   Smartphone  Electronics     45   800.0
3         104      Monitor  Electronics     20   300.0

 give the query to find employees having more than 75000 salary

   id     name   department  salary
0   1    Alice  Engineering   90000
1   3  Charlie  Engineering   95000

give sql query to display employees in descending order as per their salary

   id     name   department  salary
0   3  Charlie  Engineering   95000
1   1    Alice  Engineering   90000
2   2      Bob        Sales   70000
3   4    Diana    Marketing   65000

now give query to calculate average salary for each department

    department  average_salary
0  Engineering         92500.0
1    Marketing         65000.0
2        Sales         70000.0

query to find the name of department having more than one employee

    department  employee_count
0  Engineering               2

Display products whose price exceeds 500. Give query for it.

   product_id product_name     category  stock   price
0         101       Laptop  Electronics     15  1200.0
1         103   Smartphone  Electronics     45   800.0

Calculate the total value of all product stock using stock × price.

   total_inventory_value
0                64500.0

give join query to find employees working in the same department

    department employee_1 employee_2
0  Engineering      Alice    Charlie

query to combine the employees and products with the prices

       name  salary product_name   price
0     Alice   90000       Laptop  1200.0
1     Alice   90000   Desk Chair   150.0
2     Alice   90000   Smartphone   800.0
3     Alice   90000      Monitor   300.0
4       Bob   70000       Laptop  1200.0
5       Bob   70000   Desk Chair   150.0
6       Bob   70000   Smartphone   800.0
7       Bob   70000      Monitor   300.0
8   Charlie   95000       Laptop  1200.0
9   Charlie   95000   Desk Chair   150.0
10  Charlie   95000   Smartphone   800.0
11  Charlie   95000      Monitor   300.0
12    Diana   65000       Laptop  1200.0
13    Diana   65000   Desk Chair   150.0
14    Diana   65000   Smartphone   800.0
15    Diana   65000      Monitor   300.0

Find all employees and other employees working in the same department

    department employee co_worker
0  Engineering    Alice   Charlie
1  Engineering  Charlie     Alice

 Display employee names and product names

       name product_name
0     Alice       Laptop
1     Alice   Desk Chair
2     Alice   Smartphone
3     Alice      Monitor
4       Bob       Laptop
5       Bob   Desk Chair
6       Bob   Smartphone
7       Bob      Monitor
8   Charlie       Laptop
9   Charlie   Desk Chair
10  Charlie   Smartphone
11  Charlie      Monitor
12    Diana       Laptop
13    Diana   Desk Chair
14    Diana   Smartphone
15    Diana      Monitor